# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:

jobs:
  kc-version-matrix:
    name: Get last 10 Keycloak versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          VERSIONS=$( curl -L -s https://api.github.com/repos/keycloak/keycloak/tags | jq -c 'sort_by(.name)[-11:-1] | [ .[] | .version=.name | {version}]' )
          echo "::set-output name=matrix::{\"include\":$VERSIONS}"

  build:
    needs: kc-version-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.kc-version-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set version
        run: mvn versions:set -DnewVersion=$(git describe --tags)-KC${{ matrix.version }}
      - name: Build with Maven
        run: mvn -Dkeycloak.version=${{ matrix.version }} -B package --file pom.xml

      - name: Create Artifacts
        run: mkdir packages && find target/ -type f -name "keycloak-2fa-email-authenticator*" -exec cp {} packages/ \;

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Core-Utilities
          path: packages
