# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # - name: Set version
      #   run: mvn versions:set -DnewVersion=$(git describe --tags)-KC${{ matrix.version }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create Artifacts
        run: mkdir packages && find target/ -type f -name "keycloak-2fa-email-authenticator*" -exec cp {} packages/ \;

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Core-Utilities
          path: packages
